ets_fps_mmi-y += ets_fps.o
ets_fps_mmi-$(CONFIG_INPUT_MISC_EGISTEC_FPS_NAVI) += ets_navi_input.o

obj-$(CONFIG_INPUT_MISC_EGISTEC_FPS_MMI) += ets_fps_mmi.o

EXTRA_CFLAGS += -DCONFIG_INPUT_EGISTEC_FPS_POSE=0
