# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include

obj-$(CONFIG_INPUT_MISC_CHIPONE_FPS) += fpsensor_spi_tee.o
