# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
ccflags-y := -I$(srctree)/drivers/power/mmi_charger

mmi_discrete_charger-objs += mmi_discrete_charger_core.o
mmi_discrete_charger-objs += mmi_discrete_charger_iio.o
mmi_discrete_charger-objs += mmi_discrete_voter.o
mmi_discrete_charger-objs += mmi_discrete_factory_tcmd.o
obj-$(CONFIG_MMI_DISCRETE_CHARGER) += mmi_discrete_charger.o

obj-$(CONFIG_MMI_DISCRETE_CHARGER_CLASS) += mmi_discrete_charger_class.o
