# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall

ifneq ($(filter m y,$(CONFIG_EGIS_PANEL_NOTIFICATIONS)),)
    EXTRA_CFLAGS += -DCONFIG_PANEL_NOTIFICATIONS
endif

ifneq ($(filter m y,$(CONFIG_ET721_FOD)),)
    EXTRA_CFLAGS += -DET721_FOD
endif

rbs_fps_mmi-objs += etxxx_fp.o


obj-$(CONFIG_INPUT_EGIS_FPS_MMI) += rbs_fps_mmi.o

