# add -Wall to try to catch everything we can.
ifneq ($(filter m y,$(CONFIG_MMI_QC3P_TURBO_CHARGER_ISP_5G)),)
    EXTRA_CFLAGS += -DCONFIG_MMI_QC3P_TURBO_CHARGER_ISP_5G
endif
mmi_qc3p_wt6670f-objs += wt6670f_qc3p.o wt6670f_upgrade.o
obj-$(CONFIG_MMI_QC3P_WT6670F) += mmi_qc3p_wt6670f.o
