# add -Wall to try to catch everything we can.
ifneq ($(filter m y,$(CONFIG_AF_NOISE_ELIMINATION)),)
	EXTRA_CFLAGS += -DCONFIG_AF_NOISE_ELIMINATION
endif

EXTRA_CFLAGS += -Wall

obj-$(CONFIG_AW8695_HAPTIC) += aw8695.o
